BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20  # pixels per cell

WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3   # the upper part
SOLDIER_FEET_ROWS = 1

SOLDIER_HEIGHT = (SOLDIER_BODY_ROWS + SOLDIER_FEET_ROWS)*CELL_SIZE
SOLDIER_WIDTH = SOLDIER_COLS * CELL_SIZE

FLAG_ROWS = 3
FLAG_COLS = 4
FlAG_PLACE = (WINDOW_WIDTH - (FLAG_COLS * CELL_SIZE),WINDOW_HEIGHT - (FLAG_ROWS * CELL_SIZE))

GRASS_ROWS = 2
GRASS_COLS = 2
GRASS_SIZE = (CELL_SIZE*GRASS_ROWS,CELL_SIZE*GRASS_COLS)
grass_place = []
GRASS_COUNT = 20

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

EMPTY_CELL = "empty"
FLAG_CELL = "flag"
BOMB_CELL = "bomb"

SOLDIER_IMG = "bin/soldier.png"
NIGHT_SOLDIER_IMG = "bin/soldier_night.png"
FLAG_IMG = "bin/flag.png"
GRASS_IMG = "bin/grass.png"
BOMB_IMG = "bin/mine.png"



GREEN = (0,70,0)
SOLDIER_CELL = "soldier"

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

DOWN = "down"
UP = "up"
LEFT = "left"
RIGHT = "right"

bomb_list = []
BOMBS_AMOUNT = 20
BOMB_LEN = 3
